[package]
name = "uniffi-bindgen"
description = "UniFFI binding generator"
keywords = { workspace = true }
categories = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
publish = false

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"
doc = false

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
