name: publish npm @oicana/browser

on:
  workflow_dispatch:
  push:
    tags:
      - 'oicana_browser-v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@ce678459e9fc7500d337468f904b95f1b5c10b5e # 1.98.1
        with:
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172 # v2
        with:
          tool: wasm-pack
      - name: Build wasm
        run: npm run build:wasm
        working-directory: integrations/browser/oicana-browser
      - name: Install dependencies
        run: npm i
        working-directory: integrations/browser/oicana-browser
      - name: Build
        run: npm run build
        working-directory: integrations/browser/oicana-browser
      - name: Pack
        run: npm pack
        working-directory: integrations/browser/oicana-browser
      - name: version
        id: version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        working-directory: integrations/browser/oicana-browser
      - uses: actions/upload-artifact@v7
        with:
          name: "oicana-browser-${{ steps.version.outputs.version }}.tgz"
          path: integrations/browser/oicana-browser/oicana-browser-*.tgz
      - name: Publish
        run: |
          name=$(node -p "require('./package.json').name")
          version=$(node -p "require('./package.json').version")

          echo "Checking if $name@$version already exists:"
          if npm view "$name@$version" > /dev/null 2>&1; then
            echo "Version $version already exists on npmjs. Not publishing."
            exit 0
          fi
          echo "Version $version not found on npmjs. Proceeding to publish..."

          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "No OIDC token available, the job is missing 'permissions: id-token: write'."
            exit 1
          fi

          if echo "$version" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+$";
          then
            npm publish --access public
          elif echo "$version" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+";
          then
            npm publish --access public --tag next
          fi
        working-directory: integrations/browser/oicana-browser
